project_id = "waslpdqekbwxptwgpjze"

[functions.send-password-reset]
verify_jwt = false

[functions.collage]
verify_jwt = false

[functions.parciais]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true
