// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waslpdqekbwxptwgpjze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indhc2xwZHFla2J3eHB0d2dwanplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MjQ1MjYsImV4cCI6MjA3MTEwMDUyNn0.Za2kdeaXnASZFNdeGb_o9lpHYpQ4J2SBR0_1MuZbHus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});